from __future__ import annotations

import hashlib
import json
import os
import tempfile
from pathlib import Path
from typing import Any

from awf.core.spec_loader import _parse_agent_frontmatter


_MANIFEST_NAME = ".awf-generated-agents.json"
_TOOL_MAP = {
    "read": "read",
    "grep": "grep",
    "glob": "glob",
    "edit": "edit",
    "write": "write",
    "bash": "bash",
    "agent": "task",
    "task": "task",
    "websearch": "web_search",
    "web_search": "web_search",
    "todowrite": "todo",
    "todo": "todo",
    "askuserquestion": "ask",
    "ask": "ask",
}


def _tool_names(value: Any) -> list[str]:
    if isinstance(value, list):
        raw = [str(item) for item in value]
    else:
        raw = str(value or "").split(",")
    normalized: list[str] = []
    for item in raw:
        key = item.strip().replace("-", "_").lower()
        mapped = _TOOL_MAP.get(key)
        if mapped and mapped not in normalized:
            normalized.append(mapped)
    return normalized


def compile_claude_agent(source: Path) -> tuple[str, str]:
    meta, body = _parse_agent_frontmatter(source.read_text(encoding="utf-8"))
    name = str(meta.get("name") or source.stem).strip()
    description = str(meta.get("description") or "").strip()
    if not name or not description:
        raise ValueError(f"agent requires name and description: {source}")

    lines = ["---", f"name: {name}", f"description: {json.dumps(description, ensure_ascii=False)}"]
    tools = _tool_names(meta.get("tools"))
    if tools:
        lines.append(f"tools: {', '.join(tools)}")
    omp_model_role = str(meta.get("omp_model_role") or "").strip().removeprefix("@").strip()
    if omp_model_role:
        lines.append(f"model: {json.dumps(f'@{omp_model_role}')}")
    else:
        model = str(meta.get("model") or "").strip()
        # Claude Code role aliases are not portable model IDs. Without an
        # explicit OMP role, omit them so the task inherits the coordinator.
        if model and model.lower() not in {"sonnet", "opus", "haiku", "inherit"}:
            lines.append(f"model: {model}")
    if "task" in tools:
        lines.append("spawns: *")
    lines.extend(
        [
            "---",
            "",
            "<!-- Generated by `awf agents sync-omp`; edit the Claude source file instead. -->",
            "",
            body.rstrip(),
            "",
        ]
    )
    return name, "\n".join(lines)


def _read_manifest(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return value if isinstance(value, dict) else {}


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
        delete=False,
    ) as handle:
        handle.write(content)
        temp_path = Path(handle.name)
    os.replace(temp_path, path)


def sync_omp_agents(
    repo_root: str | os.PathLike[str],
    *,
    dry_run: bool = False,
    force: bool = False,
) -> dict[str, Any]:
    root = Path(repo_root).resolve()
    source_dirs = [root / "claude" / "agents", root / ".claude" / "agents"]
    sources: list[Path] = []
    for source_dir in source_dirs:
        if source_dir.is_dir():
            sources.extend(sorted(source_dir.glob("*.md")))
    if not sources:
        raise FileNotFoundError(f"no Claude agent definitions found under {root}")

    compiled: dict[str, tuple[Path, str]] = {}
    for source in sources:
        name, content = compile_claude_agent(source)
        compiled.setdefault(name, (source, content))

    target_dir = root / ".omp" / "agents"
    manifest_path = target_dir / _MANIFEST_NAME
    previous = _read_manifest(manifest_path)
    previous_files = {
        str(item.get("name"))
        for item in previous.get("files", [])
        if isinstance(item, dict) and item.get("name")
    }

    created: list[str] = []
    updated: list[str] = []
    unchanged: list[str] = []
    removed: list[str] = []
    conflicts = sorted(
        f"{name}.md"
        for name in compiled
        if (target_dir / f"{name}.md").exists()
        and f"{name}.md" not in previous_files
        and not force
    )
    apply_changes = not dry_run and not conflicts
    manifest_files: list[dict[str, str]] = []

    for name, (source, content) in sorted(compiled.items()):
        filename = f"{name}.md"
        target = target_dir / filename
        if not target.exists():
            created.append(filename)
        elif target.read_text(encoding="utf-8") != content:
            updated.append(filename)
        else:
            unchanged.append(filename)
        manifest_files.append(
            {
                "name": filename,
                "source": str(source.relative_to(root)),
                "sha256": hashlib.sha256(content.encode("utf-8")).hexdigest(),
            }
        )
        if apply_changes:
            _atomic_write(target, content)

    generated_names = {f"{name}.md" for name in compiled}
    for filename in sorted(previous_files - generated_names):
        target = target_dir / filename
        if target.is_file():
            removed.append(filename)
            if apply_changes:
                target.unlink()

    manifest = {
        "schema_version": 1,
        "generator": "awf agents sync-omp",
        "source_roots": [str(path.relative_to(root)) for path in source_dirs if path.is_dir()],
        "files": manifest_files,
    }
    if apply_changes:
        _atomic_write(
            manifest_path,
            json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        )

    return {
        "repo_root": str(root),
        "target_dir": str(target_dir),
        "dry_run": dry_run,
        "created": created,
        "updated": updated,
        "unchanged": unchanged,
        "removed": removed,
        "conflicts": conflicts,
        "generated_count": len(manifest_files),
    }
