"""Workflow spec-kit acceptance tests — WF-TEST-004.

Scope: G1 gate deterministic evaluation — artifact existence, FR-NNN
cross-reference coverage, constitution path resolution, [NEEDS CLARIFICATION]
markers. The G1 gate requires 4 core artifacts (spec/plan/tasks/test-criteria)
and optionally validates constitution via manifest. The 5th artifact
(constitution) is generated by the plan SKILL.md prompt, not enforced by
the gate; constitution gate-check only fires when manifest.constitution_path
is set.

Reference: docs/tests/workflow-and-multi-agent.md § WF-TEST-004
"""
from __future__ import annotations

import json
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from awf.core.db_validation import run_database_check
from awf.core.gates import _extract_fr_ids, _extract_fr_tags, evaluate_plan_gate


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_project(
    tmp: Path,
    *,
    spec: str = "",
    plan: str = "",
    tasks: str = "",
    test_criteria: str = "",
    constitution: str | None = None,
    manifest: dict | None = None,
    omit: set[str] | None = None,
) -> Path:
    """Build a minimal .workflow/artifacts/ layout in a temp directory."""
    artifacts = tmp / ".workflow" / "artifacts"
    artifacts.mkdir(parents=True, exist_ok=True)

    omit = omit or set()
    files: dict[str, str] = {
        "spec.md": spec,
        "plan.md": plan,
        "tasks.md": tasks,
        "test-criteria.md": test_criteria,
    }
    for name, content in files.items():
        if name not in omit:
            (artifacts / name).write_text(content, encoding="utf-8")

    if constitution is not None:
        const_path = tmp / ".workflow" / "constitution.md"
        const_path.write_text(constitution, encoding="utf-8")
        if manifest is None:
            manifest = {"constitution_path": ".workflow/constitution.md"}

    if manifest is not None:
        manifest_path = tmp / ".workflow" / "manifest.json"
        manifest_path.write_text(json.dumps(manifest), encoding="utf-8")

    return tmp


# ===========================================================================
# WF-TEST-004: spec-kit 루틴 — 산출물 존재 + G1 gate
# ===========================================================================


def test_004_all_5_artifacts_pass():
    """5개 산출물(spec/plan/tasks/test-criteria + constitution) 모두 존재 → G1 PASS."""
    with tempfile.TemporaryDirectory() as tmp:
        root = _make_project(
            Path(tmp),
            spec="# Spec\n## FR-001\nLogin feature\n## FR-002\nLogout feature",
            plan="# Plan\n[FR-001] Implement login\n[FR-002] Implement logout",
            tasks="# Tasks\n- [ ] T01 [FR-001] Login\n- [ ] T02 [FR-002] Logout",
            test_criteria="# Test\n[FR-001] Login test\n[FR-002] Logout test",
            constitution="# Constitution\n- MUST follow REST conventions",
        )
        passed, evals = evaluate_plan_gate(root)
        assert passed, f"G1 should PASS: {evals}"
        # 4 existence + 0 NC + 1 task + 3 FR cross-ref + 1 constitution = 9
        assert len(evals) >= 8


def test_004_missing_spec_fails():
    """spec.md 누락 → G1 FAIL."""
    with tempfile.TemporaryDirectory() as tmp:
        root = _make_project(
            Path(tmp),
            plan="plan",
            tasks="- [ ] T01 task",
            test_criteria="criteria",
            omit={"spec.md"},
        )
        passed, evals = evaluate_plan_gate(root)
        assert not passed
        spec_eval = next(e for e in evals if "spec.md" in e["condition"])
        assert not spec_eval["passed"]


def test_004_missing_tasks_fails():
    """tasks.md 누락 → G1 FAIL."""
    with tempfile.TemporaryDirectory() as tmp:
        root = _make_project(
            Path(tmp),
            spec="spec",
            plan="plan",
            test_criteria="criteria",
            omit={"tasks.md"},
        )
        passed, evals = evaluate_plan_gate(root)
        assert not passed


def test_004_missing_plan_fails():
    """plan.md 누락 → G1 FAIL."""
    with tempfile.TemporaryDirectory() as tmp:
        root = _make_project(
            Path(tmp),
            spec="spec",
            tasks="- [ ] T01 task",
            test_criteria="criteria",
            omit={"plan.md"},
        )
        passed, evals = evaluate_plan_gate(root)
        assert not passed


def test_004_missing_test_criteria_fails():
    """test-criteria.md 누락 → G1 FAIL."""
    with tempfile.TemporaryDirectory() as tmp:
        root = _make_project(
            Path(tmp),
            spec="spec",
            plan="plan",
            tasks="- [ ] T01 task",
            omit={"test-criteria.md"},
        )
        passed, evals = evaluate_plan_gate(root)
        assert not passed


def test_004_empty_spec_still_passes():
    """빈 spec (FR-NNN 없음) → FR cross-ref skip → tasks >= 1이면 PASS."""
    with tempfile.TemporaryDirectory() as tmp:
        root = _make_project(
            Path(tmp),
            spec="# Spec\nNo FR IDs here.",
            plan="# Plan",
            tasks="# Tasks\n- [ ] T01 Do something",
            test_criteria="# Test Criteria",
        )
        passed, evals = evaluate_plan_gate(root)
        assert passed


def test_004_needs_clarification_marker_fails():
    """spec.md에 [NEEDS CLARIFICATION] → G1 FAIL."""
    with tempfile.TemporaryDirectory() as tmp:
        root = _make_project(
            Path(tmp),
            spec="# Spec\n## FR-001\nFeature [NEEDS CLARIFICATION] details",
            plan="# Plan\n[FR-001] Implement",
            tasks="# Tasks\n- [ ] T01 [FR-001] Do it",
            test_criteria="# Test\n[FR-001] Check",
        )
        passed, evals = evaluate_plan_gate(root)
        assert not passed
        nc_eval = next(e for e in evals if "NEEDS CLARIFICATION" in e["condition"])
        assert not nc_eval["passed"]


def test_004_zero_tasks_fails():
    """tasks.md에 task 항목이 0개 → G1 FAIL."""
    with tempfile.TemporaryDirectory() as tmp:
        root = _make_project(
            Path(tmp),
            spec="# Spec\nSome text",
            plan="# Plan",
            tasks="# Tasks\nNothing here yet.",
            test_criteria="# Test",
        )
        passed, evals = evaluate_plan_gate(root)
        assert not passed
        task_eval = next(e for e in evals if ">= 1 task" in e["condition"])
        assert not task_eval["passed"]


def test_004_fr_cross_ref_plan_missing():
    """plan.md에서 FR-002 누락 → G1 FAIL."""
    with tempfile.TemporaryDirectory() as tmp:
        root = _make_project(
            Path(tmp),
            spec="# Spec\n## FR-001\nA\n## FR-002\nB",
            plan="# Plan\n[FR-001] Only first",
            tasks="# Tasks\n- [ ] T01 [FR-001, FR-002] Both",
            test_criteria="# Test\n[FR-001, FR-002] Both",
        )
        passed, evals = evaluate_plan_gate(root)
        assert not passed
        plan_eval = next(e for e in evals if "tagged in plan.md" in e["condition"])
        assert not plan_eval["passed"]
        assert "FR-002" in plan_eval["detail"]


def test_004_fr_cross_ref_tasks_missing():
    """tasks.md에서 FR-001 누락 → G1 FAIL."""
    with tempfile.TemporaryDirectory() as tmp:
        root = _make_project(
            Path(tmp),
            spec="# Spec\n## FR-001\nA\n## FR-002\nB",
            plan="# Plan\n[FR-001, FR-002] Both",
            tasks="# Tasks\n- [ ] T01 [FR-002] Only second",
            test_criteria="# Test\n[FR-001, FR-002] Both",
        )
        passed, evals = evaluate_plan_gate(root)
        assert not passed
        tasks_eval = next(e for e in evals if "tagged in tasks.md" in e["condition"])
        assert not tasks_eval["passed"]


def test_004_fr_cross_ref_criteria_missing():
    """test-criteria.md에서 FR-003 누락 → G1 FAIL."""
    with tempfile.TemporaryDirectory() as tmp:
        root = _make_project(
            Path(tmp),
            spec="# Spec\n## FR-001\nA\n## FR-003\nC",
            plan="# Plan\n[FR-001, FR-003] Both",
            tasks="# Tasks\n- [ ] T01 [FR-001, FR-003] Both",
            test_criteria="# Test\n[FR-001] Only first",
        )
        passed, evals = evaluate_plan_gate(root)
        assert not passed
        criteria_eval = next(e for e in evals if "tagged in test-criteria.md" in e["condition"])
        assert not criteria_eval["passed"]


def test_004_constitution_loaded_when_manifest_set():
    """manifest.constitution_path가 존재하고 파일 있음 → G1 PASS."""
    with tempfile.TemporaryDirectory() as tmp:
        root = _make_project(
            Path(tmp),
            spec="# Spec\nNo FR IDs",
            plan="# Plan",
            tasks="# Tasks\n- [ ] T01 Do it",
            test_criteria="# Test",
            constitution="# Rules\n- MUST use HTTPS",
        )
        passed, evals = evaluate_plan_gate(root)
        assert passed
        const_eval = next((e for e in evals if "constitution" in e["condition"]), None)
        assert const_eval is not None
        assert const_eval["passed"]


def test_004_constitution_missing_file_fails():
    """manifest에 constitution_path 설정했지만 파일 없음 → G1 FAIL."""
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        artifacts = root / ".workflow" / "artifacts"
        artifacts.mkdir(parents=True)
        for name in ("spec.md", "plan.md", "test-criteria.md"):
            (artifacts / name).write_text("content", encoding="utf-8")
        (artifacts / "tasks.md").write_text("- [ ] T01 task", encoding="utf-8")

        manifest = {"constitution_path": ".workflow/does-not-exist.md"}
        (root / ".workflow" / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")

        passed, evals = evaluate_plan_gate(root)
        assert not passed


def test_004_no_manifest_skips_constitution_check():
    """manifest 없으면 constitution check 자체가 없음 → PASS 가능."""
    with tempfile.TemporaryDirectory() as tmp:
        root = _make_project(
            Path(tmp),
            spec="# Spec",
            plan="# Plan",
            tasks="# Tasks\n- [ ] T01 task",
            test_criteria="# Test",
        )
        passed, evals = evaluate_plan_gate(root)
        assert passed
        assert not any("constitution" in e["condition"] for e in evals)


# ---------------------------------------------------------------------------
# P0 database evidence: G1 mandatory conditions
# ---------------------------------------------------------------------------

def _database_command(payload: dict[str, object]) -> list[str]:
    return [sys.executable, "-c", f"print({json.dumps(payload)!r})"]


def _database_schema() -> dict[str, object]:
    return {
        "schema_version": 1,
        "kind": "production_schema",
        "target_class": "production_metadata",
        "read_only": True,
        "schema_only": True,
        "engine": "mysql",
        "engine_version": "8.0",
        "captured_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "schema_hash": "a" * 64,
        "object_counts": {"tables": 1, "columns": 8, "indexes": 2, "constraints": 3},
    }


def _database_decision() -> dict[str, object]:
    baseline = {
        "id": "maintain-current",
        "kind": "maintain",
        "applicable": True,
        "summary": "Keep the current query",
        "equivalence_plan": "Use the current result set",
        "integrity_plan": "Verify existing constraints",
        "normalization_assessment": "No model change",
        "read_write_cost": "Measure production-shaped workload",
        "operational_risks": [],
        "transition_risks": [],
        "rollback_or_exit": "No change",
        "unavailable_reason": None,
        "denormalization_assessment": None,
        "physical_design_assessment": None,
    }
    rewrite = {
        "id": "rewrite-query",
        "kind": "query_change",
        "applicable": True,
        "summary": "Rewrite the aggregation query",
        "equivalence_plan": "Compare baseline results",
        "integrity_plan": "Verify constraints before and after",
        "normalization_assessment": "No model change",
        "read_write_cost": "Measure latency on production-shaped workload",
        "operational_risks": [],
        "transition_risks": [],
        "rollback_or_exit": "Restore the current query",
        "unavailable_reason": None,
        "denormalization_assessment": None,
        "physical_design_assessment": None,
    }
    return {
        "schema_version": 1,
        "status": "selected",
        "change_surfaces": ["query"],
        "baseline_option_id": "maintain-current",
        "recommended_option_id": "rewrite-query",
        "selected_option_id": "rewrite-query",
        "candidates": [baseline, rewrite],
        "recommendation_rationale": "Preserves correctness at the lowest lifecycle cost.",
    }


def _database_plan_project(tmp: Path) -> tuple[Path, Path]:
    root = _make_project(
        tmp,
        spec="Database query change",
        plan="Compare the database query options",
        tasks="- [ ] T01 Implement the selected query",
        test_criteria="Verify query result equivalence",
    )
    workflow = root / ".workflow"
    artifacts = workflow / "artifacts"
    (workflow / "manifest.json").write_text(
        json.dumps(
            {
                "database_validation": {
                    "enabled": True,
                    "schema_command": _database_command(_database_schema()),
                    "verify_command": [],
                    "test_command": [],
                    "command_timeout_seconds": 5,
                    "max_schema_age_hours": 24,
                    "allow_production_replica_sample": False,
                }
            }
        ),
        encoding="utf-8",
    )
    (artifacts / "database-decision.json").write_text(
        json.dumps(_database_decision()),
        encoding="utf-8",
    )
    result = run_database_check(root, "plan")
    assert result.status == "pass"
    return root, artifacts / "database-validation-evidence.json"


def _evaluation_by_condition(evaluations: list[dict[str, object]]) -> dict[str, dict[str, object]]:
    return {str(item["condition"]): item for item in evaluations}


def test_database_g1_valid_plan_evidence_passes() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root, _ = _database_plan_project(Path(tmp))

        passed, evaluations = evaluate_plan_gate(root)

        assert passed, evaluations
        checks = _evaluation_by_condition(evaluations)
        assert checks["database.signal"]["passed"] is True
        assert checks["database.risk_class"]["passed"] is True
        assert checks["database.decision"]["passed"] is True
        assert checks["database.production_schema"]["passed"] is True


def test_database_g1_missing_decision_fails() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root, _ = _database_plan_project(Path(tmp))
        (root / ".workflow" / "artifacts" / "database-decision.json").unlink()

        passed, evaluations = evaluate_plan_gate(root)

        assert not passed
        assert _evaluation_by_condition(evaluations)["database.decision"]["passed"] is False


def test_database_g1_missing_plan_evidence_fails() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root, evidence = _database_plan_project(Path(tmp))
        evidence.unlink()

        passed, evaluations = evaluate_plan_gate(root)

        assert not passed
        assert _evaluation_by_condition(evaluations)["database.production_schema"]["passed"] is False


def test_database_g1_stale_plan_evidence_fails() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root, evidence_path = _database_plan_project(Path(tmp))
        evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
        evidence["stages"]["plan"]["schema"]["captured_at"] = "2000-01-01T00:00:00Z"
        evidence_path.write_text(json.dumps(evidence), encoding="utf-8")

        passed, evaluations = evaluate_plan_gate(root)

        assert not passed
        assert _evaluation_by_condition(evaluations)["database.production_schema"]["passed"] is False


def test_database_g1_profile_hash_mismatch_fails() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root, evidence_path = _database_plan_project(Path(tmp))
        evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
        evidence["profile_hash"] = "b" * 64
        evidence_path.write_text(json.dumps(evidence), encoding="utf-8")

        passed, evaluations = evaluate_plan_gate(root)

        assert not passed
        assert _evaluation_by_condition(evaluations)["database.production_schema"]["passed"] is False


def test_database_g1_non_high_risk_evidence_fails() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root, evidence_path = _database_plan_project(Path(tmp))
        evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
        evidence["change_class"] = "small"
        evidence_path.write_text(json.dumps(evidence), encoding="utf-8")

        passed, evaluations = evaluate_plan_gate(root)

        assert not passed
        assert _evaluation_by_condition(evaluations)["database.risk_class"]["passed"] is False


def test_database_g1_no_signal_remains_not_applicable() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root = _make_project(
            Path(tmp),
            spec="Plain user-interface copy change",
            plan="Update the label",
            tasks="- [ ] T01 Update the label",
            test_criteria="Render the label",
        )

        passed, evaluations = evaluate_plan_gate(root)

        assert passed, evaluations
        signal = _evaluation_by_condition(evaluations)["database.signal"]
        assert signal["passed"] is True
        assert signal["detail"] == "status=not_applicable"
# ---------------------------------------------------------------------------
# Utility function tests
# ---------------------------------------------------------------------------


def test_extract_fr_ids():
    assert _extract_fr_ids("FR-001 and FR-002 are required") == {"FR-001", "FR-002"}
    assert _extract_fr_ids("No IDs here") == set()
    assert _extract_fr_ids("FR-100, FR-100 duplicate") == {"FR-100"}


def test_extract_fr_tags():
    assert _extract_fr_tags("[FR-001, FR-002] Implement") == {"FR-001", "FR-002"}
    assert _extract_fr_tags("[FR-001] and [FR-003]") == {"FR-001", "FR-003"}
    assert _extract_fr_tags("No brackets") == set()


# ===========================================================================
# Runner
# ===========================================================================


def main() -> int:
    tests = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    passed = 0
    failed = 0

    print("\n--- WF-TEST-004: spec-kit G1 gate ---")
    for test_fn in tests:
        name = test_fn.__name__
        try:
            test_fn()
            print(f"  PASS  {name}")
            passed += 1
        except Exception as exc:
            print(f"  FAIL  {name}: {exc}")
            failed += 1

    print(f"\n{'='*40}")
    print(f"{passed} passed, {failed} failed")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
