"""`awf wf pr` — create a GitHub PR for the current workflow cycle (§3.4).

The 2026-05-13 BLIP Gem cycle ended with PR creation as a manual step;
this command condenses cycle metadata (id, gates, concept) into a PR
title/body so the operator only confirms.

Implementation notes:
- Calls `gh pr create` via subprocess. Requires `gh` on PATH and an
  authenticated session (we surface gh's error directly when missing).
- Title format: `<workflow id> — <concept first line>`.
- Body sections: cycle summary, gate matrix, optional concept excerpt.
- Flags: `--base` (default `main`), `--draft`, `--no-fill` (skip auto
  body), `--dry-run` (print proposed args without invoking gh).
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

from awf.core.state import load_workflow_state, find_repo_root


GATE_LABEL = {
    "G1": "plan",
    "G2": "review",
    "G3": "approve",
    "G4": "impl",
    "G5": "verify",
    "G6": "test",
}


def _read_concept_excerpt(repo_root: Path, max_lines: int = 30) -> str:
    """Pull the first ~30 lines of `.workflow/concept.md` for the PR body."""
    concept_path = repo_root / ".workflow" / "concept.md"
    if not concept_path.is_file():
        return ""
    lines = concept_path.read_text(encoding="utf-8").splitlines()[:max_lines]
    return "\n".join(lines).strip()


def _gate_marker(entry: object) -> str:
    if not isinstance(entry, dict):
        return "—"
    passed = entry.get("passed")
    if passed is True:
        return "✅"
    if passed is False:
        return "❌"
    return "—"


def _build_title(state: dict, override: str | None) -> str:
    if override:
        return override
    cycle_id = str(state.get("id") or "workflow-cycle")
    return f"{cycle_id}"


def _build_body(state: dict, repo_root: Path) -> str:
    cycle_id = str(state.get("id") or "unknown")
    branch = str(state.get("branch") or "")
    change_class = str(state.get("changeClass") or "")
    current_phase = str(state.get("currentPhase") or "")
    total_executions = int(state.get("totalExecutions") or 0)

    gates = state.get("gates") or {}
    gate_rows = [
        f"| {gate_id} | {GATE_LABEL.get(gate_id, '-')} | {_gate_marker(gates.get(gate_id))} |"
        for gate_id in ("G1", "G2", "G3", "G4", "G5", "G6")
    ]

    parts: list[str] = [
        "## Summary",
        f"- Cycle: `{cycle_id}`",
        f"- Branch: `{branch}`",
        f"- Change class: `{change_class}`",
        f"- Current phase: `{current_phase}`",
        f"- Total executions: {total_executions}",
        "",
        "## Gates",
        "",
        "| Gate | Phase | Result |",
        "|------|-------|--------|",
        *gate_rows,
    ]

    excerpt = _read_concept_excerpt(repo_root)
    if excerpt:
        parts.extend(["", "## Concept", "", excerpt])

    parts.extend([
        "",
        "🤖 Generated by `awf wf pr`",
    ])
    return "\n".join(parts).rstrip() + "\n"


def _gh_available() -> bool:
    return shutil.which("gh") is not None


def run_wf_pr(args: argparse.Namespace) -> int:
    try:
        repo_root = find_repo_root(args.repo_root)
    except Exception as exc:
        print(f"error: cannot resolve repo root: {exc}", file=sys.stderr)
        return 2

    try:
        state = load_workflow_state(args.repo_root)
    except FileNotFoundError as exc:
        print(f"error: {exc}", file=sys.stderr)
        print("  hint: run `awf wf init` to start a workflow first.", file=sys.stderr)
        return 2

    title = _build_title(state, getattr(args, "title", None))
    body: str = ""
    if not getattr(args, "no_fill", False):
        body = getattr(args, "body", None) or _build_body(state, repo_root)

    base = getattr(args, "base", None) or "main"
    draft = bool(getattr(args, "draft", False))
    dry_run = bool(getattr(args, "dry_run", False))

    cmd = ["gh", "pr", "create", "--base", base, "--title", title]
    if body:
        cmd.extend(["--body", body])
    if draft:
        cmd.append("--draft")

    if dry_run:
        # Print what would run; useful for previewing the body in CI.
        print("dry-run gh pr create:")
        print(f"  base : {base}")
        print(f"  title: {title}")
        if body:
            print("  body :")
            for line in body.splitlines():
                print(f"    {line}")
        return 0

    if not _gh_available():
        print("error: `gh` CLI not found on PATH. Install GitHub CLI first.", file=sys.stderr)
        return 2

    try:
        completed = subprocess.run(
            cmd,
            cwd=str(repo_root),
            text=True,
            capture_output=True,
            timeout=60,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        print(f"error: `gh pr create` failed to launch: {exc}", file=sys.stderr)
        return 2

    if completed.returncode != 0:
        stderr = (completed.stderr or "").strip()
        print(f"error: gh exited {completed.returncode}: {stderr}", file=sys.stderr)
        return completed.returncode

    url = (completed.stdout or "").strip()
    if url:
        print(url)
    return 0
